"use client";

import React, { useState, useEffect } from 'react';
import Link from 'next/link';

export default function DailyBriefingPage() {
    const [briefing, setBriefing] = useState("");
    const [loading, setLoading] = useState(false);

    const getBriefing = async () => {
        setLoading(true);
        try {
            const res = await fetch('http://localhost:3001/api/briefing');
            const data = await res.json();
            setBriefing(data.briefing);
        } catch (e) {
            setBriefing("Report load nahi ho saki.");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        getBriefing();
    }, []);

    return (
        <div className="min-h-screen bg-white font-sans text-gray-900">
            <nav className="p-6 border-b flex justify-between items-center bg-gray-50">
                <Link href="/" className="text-sm font-bold text-blue-600 uppercase tracking-widest">← Back to Home</Link>
                <h1 className="text-lg font-black uppercase">Daily Summary Report</h1>
                <div className="w-24"></div>
            </nav>

            <main className="max-w-3xl mx-auto p-10">
                <div className="bg-gray-50 rounded-[40px] p-12 border border-gray-100 shadow-2xl relative overflow-hidden">
                    {/* Decorative Elements */}
                    <div className="absolute top-0 right-0 w-32 h-32 bg-blue-100 rounded-bl-full opacity-50"></div>
                    
                    <header className="mb-10">
                        <p className="text-xs font-black text-blue-500 uppercase mb-2 tracking-[0.3em]">AI Assistant Analysis</p>
                        <h2 className="text-4xl font-black text-gray-800 leading-tight">Aaj ki Briefing,<br/>Abdul Rafay.</h2>
                        <div className="mt-4 h-1 w-20 bg-blue-600 rounded-full"></div>
                    </header>

                    {loading ? (
                        <div className="flex flex-col items-center py-20">
                            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mb-4"></div>
                            <p className="text-gray-400 font-bold text-xs uppercase tracking-widest">Saim is analyzing your day...</p>
                        </div>
                    ) : (
                        <div className="prose prose-blue">
                            <p className="text-lg text-gray-700 leading-relaxed font-medium whitespace-pre-wrap italic">
                                {briefing || "Aaj koi activity record nahi hui."}
                            </p>
                        </div>
                    )}

                    <footer className="mt-16 pt-8 border-t border-gray-200 flex justify-between items-center">
                        <button 
                            onClick={getBriefing} 
                            className="bg-gray-900 text-white px-8 py-3 rounded-full text-xs font-bold uppercase tracking-widest hover:bg-blue-600 transition-all active:scale-95"
                        >
                            Regenerate Report
                        </button>
                        <span className="text-[10px] font-bold text-gray-400 uppercase">Generated by Saim AI</span>
                    </footer>
                </div>
            </main>
        </div>
    );
}
